version: "3.9"
services:
  database:
    image: mcr.microsoft.com/mssql/server:2019-CU14-ubuntu-20.04
    container_name: database
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=pa55word!